export enum ActionType {
    MOVE_CELL = 'MOVE_CELL',
    DELETE_CELL = 'DELETE_CELL',
    INSERT_CELL_AFTER = 'INSERT_CELL_AFTER',
    UPDATE_CELL = 'UPDATE_CELL',
    BUNDLE_START = 'BUNDLE_START',
    BUNDLE_COMPLETE = 'BUNDLE_COMPLETE',
    LOAD_START = 'LOAD_START',
    LOAD_COMPLETE = 'LOAD_COMPLETE', 
    LOAD_ERROR = 'LOAD_ERROR'
}